# map cmd+left previous_tab # Go to previous tab
# map cmd+right next_tab # Go to next tab
# map cmd+t new_tab # Create new tab
# map kitty_mod+alt+t set_tab_title # Set tab title
active_border_color #0c0c0c

allow_remote_control yes
background_opacity 0.95
bell_on_tab yes
copy_on_select yes
cursor_beam_thickness 2.0
cursor_blink_interval -1
cursor_shape block
cursor_stop_blinking_after 15.0
cursor_underline_thickness 2.0
dim_opacity 0.50
disable_ligatures never
draw_minimal_borders yes
enable_audio_bell no
enable_audio_bell yes
# enabled_layouts tall,fat,horizontal,vertical
focus_follows_mouse yes
font_family MapleMono NF

font_size 10
hide_window_decorations yes
# inactive_border_color #0c0c0c
inactive_text_alpha 0.4
listen_on unix:/tmp/kitty

scrollback_lines 10000
shell_integration enabled no-title
url_prefixes http https file ftp git
url_style curly
wheel_scroll_multiplier 3.0
window_margin_width 2
window_padding_width 3
window_resize_step_cells 2
window_resize_step_lines 2
allow_hyperlinks yes

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted


# BEGIN_KITTY_THEME
# Tokyo Night Moon
include current-theme.conf
# END_KITTY_THEME
